# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att1', models.IntegerField()),
                ('att2', models.IntegerField()),
                ('att3', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meter.Parent')),
                ('att2', models.IntegerField()),
            ],
        ),
    ]
