# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0008_auto_20161001_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att1', models.IntegerField()),
                ('att2', models.IntegerField()),
                ('att3', models.IntegerField()),
            ],
        ),
    ]
