# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0014_auto_20161001_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('eur', 'euro'), ('usd', 'us dollar')], default='eur', max_length=6),
        ),
    ]
