# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0015_auto_20161001_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cost_kw_per_hour',
            field=models.FloatField(default=1),
        ),
    ]
