# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0016_auto_20161004_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='currency',
        ),
        migrations.AlterField(
            model_name='settings',
            name='cost_kw_per_hour',
            field=models.FloatField(default=0.19),
        ),
    ]
