# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0017_auto_20161006_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cost_liter',
            field=models.FloatField(default=0.19),
        ),
    ]
