# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0018_settings_cost_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cost_liter',
            field=models.FloatField(default=0.9),
        ),
    ]
