# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0020_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='liters_warning',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='power_warning',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
