# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0021_auto_20161007_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='liters_warning',
            new_name='water_liters_warning',
        ),
    ]
