# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0022_auto_20161007_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='cost_liter',
            new_name='cost_m3',
        ),
    ]
