# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0023_auto_20161007_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='water_liters_warning',
            new_name='cubic_meters_warning',
        ),
    ]
