# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0024_auto_20161007_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cubic_meters_warning',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_warning',
            field=models.FloatField(blank=True),
        ),
    ]
