# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0026_auto_20161007_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cubic_meters_warning',
            field=models.FloatField(blank=True, help_text='Selecionou "Enviar email". Tem de inserir um valor'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_warning',
            field=models.FloatField(blank=True, help_text='Selecionou "Enviar email". Tem de inserir um valor'),
        ),
    ]
