# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0028_auto_20161008_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cost_kw_per_hour',
            field=models.FloatField(default=0.19, validators=[django.core.validators.MinValueValidator(0.0, 'Custo da eletricidade tem de ser positivo')]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cost_m3',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0, 'Custo da \xe1gua tem de ser positivo')]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cubic_meters_warning',
            field=models.FloatField(blank=True, help_text='Selecionou "Enviar email". Tem de inserir um valor', null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_warning',
            field=models.FloatField(blank=True, help_text='Selecionou "Enviar email". Tem de inserir um valor', null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Limite de consumo el\xe9trico tem de ser positivo')]),
        ),
    ]
