# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0030_auto_20161008_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cubic_meters_warning',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, 'Limite de consumo de \xe1gua tem de ser positivo')]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_warning',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, 'Limite de consumo el\xe9trico tem de ser positivo')]),
        ),
    ]
