# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0031_auto_20161008_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='cubic_meters_warning',
            new_name='liters_warning',
        ),
    ]
